### PR TITLE
Update Kill_Them_With_Flowers.zs

### PR DESCRIPTION
**Pull request by Xukkorz**
Correcting syntax on file, was not loading scripts. Corrected manaGold sections, manaDiamond Sections, and eyeEnder recipe.

### CODE REVIEW

**Comment by Xukkorz** [comment]
Correcting syntax on file, was not loading scripts. Corrected manaGold sections, manaDiamond Sections, and eyeEnder recipe.  No other changes made.

**Comment by Xukkorz** [comment]
Also commented out duplicate variables for lava and water. Probably should be renamed but it does not appear that they are used.

**Comment by Strikingwolf** [comment]
The liquidBucket and liquid Val's are different uncomment them. Other than that this is good

**Comment by UndeadZeratul** [comment]
Even if they are different, are you using the lava and water source blocks in recipes?  Wouldn't you need the bucket version?

**Comment by Strikingwolf** [comment]
It is a possibility. Not often, but possible :laughing:

**Comment by Xukkorz** [comment]
The problem was that the variable used was the same. Changing the variable
name would be fine but when I tried to load the config in minecraft it
threw a fit so I commented them out just to fix it. I wasn't sure if there
was a specific naming convention that was being used so it made more sense
to me to just leave them there and they could be actually fixed when needed.

**Comment by Strikingwolf** [comment]
o_O I see different variable names. I see lava and lavaBucket for example

**Comment by Xukkorz** [comment]
yeah lava bucket is next to lava but later on in the file there is a second
"var lava" same with water.

**Comment by Strikingwolf** [comment]
Ah I didn't realize that @Xukkorz thanks for pointing it out. It looked to me like you thought the lavaBucket val and the lava val were the same :laughing:

**Pull request merged**
